# Generated by Django 5.0.2 on 2024-02-21 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category,s',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol', models.CharField(choices=[('momo', 'One'), ('popo', 'Two')], max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('is_discount', models.BooleanField(default=False)),
                ('at_creat', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
    ]
