# Generated by Django 5.0.2 on 2024-02-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kol',
        ),
    ]
