# Generated by Django 5.0.2 on 2024-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(default='ویژگی محصولات', max_length=800),
        ),
    ]
