# Generated by Django 5.0.2 on 2024-02-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_product_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
